DROP TABLE IF EXISTS wy1_train_user_item;
CREATE TABLE wy1_train_user_item AS 
SELECT * FROM
(
	SELECT DISTINCT user_id,item_id,1 AS label FROM user_item_detail WHERE dodate='2014-12-18 00:00:00' AND dobuy>0
	UNION ALL 
	SELECT DISTINCT user_id,item_id,0 AS label FROM user_item_detail WHERE dodate='2014-12-18 00:00:00' AND dobuy=0 LIMIT 4200000
) t;

DROP TABLE IF EXISTS wy1_train_data;
CREATE TABLE wy1_train_data AS 
SELECT a.*,
b.user_totaldays_view_total,
b.user_totaldays_favor_total,
b.user_totaldays_addcar_total,
b.user_totaldays_buy_total,
b.user_last1week_view_total,
b.user_last1week_favor_total,
b.user_last1week_addcar_total,
b.user_last3days_view_total,
b.user_last3days_favor_total,
b.user_last3days_addcar_total,
b.user_last3days_buy_total,
b.user_last_1_day_view_count,
b.user_last_1_day_favor_count,
b.user_last_1_day_addcar_count,
b.user_last_1_day_buy_count,
b.user_last_2_day_view_count,
b.user_last_2_day_favor_count,
b.user_last_2_day_addcar_count,
b.user_last_2_day_buy_count,
b.user_last_3_day_view_count,
b.user_last_3_day_favor_count,
b.user_last_3_day_addcar_count,
b.user_last_3_day_buy_count,
b.user_totaldays_dawn_total,
b.user_totaldays_am_total,
b.user_totaldays_pm_total,
b.user_last1week_dawn_total,
b.user_last1week_am_total,
b.user_last1week_pm_total,
b.user_last3days_dawn_total,
b.user_last3days_am_total,
b.user_last3days_pm_total,
b.user_last_1day_totalhour,
b.user_last_2day_totalhour,
b.user_last_3day_totalhour,
b.user_last1week_dawn_buy,
b.user_last1week_am_buy,
b.user_last1week_pm_buy,
b.user_last1week_dawn_buyrate,
b.user_last1week_am_buyrate,
b.user_last1week_pm_buyrate,
b.user_last3days_dawn_buy,
b.user_last3days_am_buy,
b.user_last3days_pm_buy,
b.user_last3days_dawn_buyrate,
b.user_last3days_am_buyrate,
b.user_last3days_pm_buyrate,
b.user_lastbuy_diffdays,
b.user_lastact_diffdays,
b.user_last1week_favor_count,
b.user_last1week_addcar_count,
b.user_last1week_favorandbuy_count,
b.user_last1week_addcarandbuy_count,
b.user_last1week_favorandbuy_rate,
b.user_last1week_addcarandbuy_rate,
b.user_last3days_favor_count,
b.user_last3days_addcar_count,
b.user_last3days_favorandbuy_count,
b.user_last3days_addcarandbuy_count,
b.user_last3days_favorandbuy_rate,
b.user_last3days_addcarandbuy_rate,
b.user_totaldays_rebuy_itemcount,
b.user_totaldays_rebuy_itemrate,
c.item_totaldays_view_total,
c.item_totaldays_dofavor_total,
c.item_totaldays_addcar_total,
c.item_totaldays_dobuy_total,
c.item_last1week_view_total,
c.item_last1week_favor_total,
c.item_last1week_addcar_total,
c.item_last1week_buy_total,
c.item_last3days_view_total,
c.item_last3days_favor_total,
c.item_last3days_addcar_total,
c.item_last3days_buy_total,
c.item_last_1_day_view_count,
c.item_last_1_day_favor_count,
c.item_last_1_day_addcar_count,
c.item_last_1_day_buy_count,
c.item_last_2_day_view_count,
c.item_last_2_day_favor_count,
c.item_last_2_day_addcar_count,
c.item_last_2_day_buy_count,
c.item_last_3_day_view_count,
c.item_last_3_day_favor_count,
c.item_last_3_day_addcar_count,
c.item_last_3_day_buy_count,
c.item_totaldays_dawn_total,
c.item_totaldays_am_total,
c.item_totaldays_pm_total,
c.item_last1week_favor_count,
c.item_last1week_addcar_count,
c.item_last1week_favorandbuy_count,
c.item_last1week_addcarandbuy_count,
c.item_last1week_favorandbuy_rate,
c.item_last1week_addcarandbuy_rate,
c.item_totaldays_rebuy_usercount,
c.user_totaldays_rebuy_userrate,
d.user_item_totaldays_view_total,
d.user_item_totaldays_favor_total,
d.user_item_totaldays_addcar_total,
d.user_item_totaldays_buy_total,
d.user_item_last1week_view_total,
d.user_item_last1week_favor_total,
d.user_item_last1week_addcar_total,
d.user_item_last1week_buy_total,
d.user_item_last3days_view_total,
d.user_item_last3days_favor_total,
d.user_item_last3days_addcar_total,
d.user_item_last3days_buy_total,
d.user_item_last_1_day_view_count,
d.user_item_last_1_day_favor_count,
d.user_item_last_1_day_addcar_count,
d.user_item_last_1_day_buy_count,
d.user_item_last_2_day_view_count,
d.user_item_last_2_day_favor_count,
d.user_item_last_2_day_addcar_count,
d.user_item_last_2_day_buy_count,
d.user_item_last_3_day_view_count,
d.user_item_last_3_day_favor_count,
d.user_item_last_3_day_addcar_count,
d.user_item_last_3_day_buy_count,
d.user_item_totaldays_dawn_total,
d.user_item_totaldays_am_total,
d.user_item_totaldays_pm_total,
d.user_item_firstact_diffdays,
d.user_item_recently_view_diffdays,
d.user_item_recently_favor_diffdays,
d.user_item_recently_addcar_diffdays,
d.user_item_recently_buy_diffdays
FROM wy1_train_user_item a 
LEFT OUTER JOIN wy1_f1 b ON a.user_id=b.user_id
LEFT OUTER JOIN wy1_f2 c ON a.item_id=c.item_id
LEFT OUTER JOIN wy1_f3 d ON a.user_id=d.user_id AND a.item_id=d.item_id;

DROP TABLE IF EXISTS wy1_train_data_filter;
CREATE TABLE wy1_train_data_filter AS 
SELECT * FROM wy1_train_data WHERE user_totaldays_view_total<25000;